mtd-cli: Fix compilation with older GCC
When compiling under CentOS 7 with GCC 4.8.5 20150623 (Red Hat 4.8.5-39)
I was getting the following compile failures

  CC    mtd-cli-test-ni.o
mtd-cli-test-ni.c:35:2: error: initializer element is not constant
  .api_name = API_NAME,
  ^
mtd-cli-test-ni.c:35:2: error: (near initialization for ‘test_ni_endpoint.api_name’)
mtd-cli-test-ni.c:37:1: error: initializer element is not constant
 };
 ^

That would be the case for all mtd-cil-*.c files. I'm not entirely sure
what it didn't like here, everything is constant at compile time,
API_NAME & CMDS are static const char * const, however they used to be
simply defined string constants. That was changed by commit 8aeed11
("mtd-cli: Re-work endpoint commands printing") in which I stated

    "For this to work we change API_NAME & ENDPOINTS from #defines to
     static const char * const's."

Now, I'm not sure why I thought that and simply changing API_NAME and
CMDS back to simple #defines fixes the build with older GCC.

Signed-off-by: Andrew Clayton <andrew@digital-domain.net>